### ISSUE TITLE
Not able to parse pos-tagger output if it contains unicode characters

### ISSUE THREAD

**Issue by nicolaslt** [opener-project/kaf2json#3]
Hi,

The following throws a SAXParseException:
```bash
echo "test 😄 test in english" | language-identifier | tokenizer | pos-tagger | kaf2json
```
Exception (full stack
[exception.txt](https://github.com/opener-project/kaf2json/files/94667/exception.txt)
 attached to this issue):
```
Error on line 27 column 11 
  SXXP0003: Error reported by XML parser: An invalid XML character (Unicode: 0xd83d) was
  found in the comment.
net/sf/saxon/s9api/DocumentBuilder.java:374:in `build': net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 11; An invalid XML character (Unicode: 0xd83d) was found in the comment.
        from java/lang/reflect/Method.java:606:in `invoke'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/saxon-xslt-0.7.2-java/lib/saxon/xml.rb:26:in `parse'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/saxon-xslt-0.7.2-java/lib/saxon/processor.rb:57:in `XML'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/saxon-xslt-0.7.2-java/lib/saxon/xml.rb:11:in `XML'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/opener-kaf2json-2.0.0-java/lib/opener/kaf_to_json.rb:27:in `run'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/opener-kaf2json-2.0.0-java/lib/opener/kaf_to_json/cli.rb:52:in `configure_slop'
        from org/jruby/RubyProc.java:271:in `call'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/opener-kaf2json-2.0.0-java/lib/opener/kaf_to_json/cli.rb:20:in `run'
        from /usr/share/jruby/lib/ruby/gems/shared/gems/opener-kaf2json-2.0.0-java/bin/kaf2json:7:in `(root)'
        from org/jruby/RubyKernel.java:1059:in `load'
        from /usr/local/bin/kaf2json:23:in `(root)'
        from usr/local/bin//usr/local/bin/kaf2json:23:in `(root)'
```

**Comment by giannismelidis** [comment]
Thanks for pointing this out, support for emojis has been added in new version (2.0.1)
